version: '3'

services:
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules

    cassandra:
        image: cassandra:latest
        container_name: cassandra
        ports:
            - "9042:9042"  # Cassandra native transport port
        environment:
            - CASSANDRA_LISTEN_ADDRESS=127.0.0.1  # Set the listen address to 127.0.0.1
            - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1  # Set the broadcast address to 127.0.0.1
            - CASSANDRA_CLUSTER_NAME=mycluster  # Set the Cassandra cluster name
            - CASSANDRA_DC=datacenter1  # Set the datacenter name
            - CASSANDRA_KEYSPACE=mykeyspace  # Set the keyspace name
        volumes:
        - ./data:/var/lib/cassandra  # Persist data to the host machine